services:
  app:
    image: ghcr.io/bariiss/url-shortener:latest
    container_name: url-shortener
    restart: always
    env_file:
      - ./.env
    ports:
      - "${EXT_PORT}:${APP_PORT}"
    depends_on:
      - redis
    volumes:
      - ./.env:/app/.env
      - ./static:/app/static # remove this line if you don't debug the static files
      - ./templates:/app/templates # remove this line if you don't debug the templates

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./redisdata:/data
